server.port=8081
spring.application.name=hr_system
spring.datasource.url=jdbc:mysql://localhost:3306/hr_system_db
spring.datasource.username=hr_user
spring.datasource.password=HrUserPass123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=admin
spring.security.user.password=123
#docker run --name my-mysql -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=hr_system_db -e MYSQL_USER=hr_user -e MYSQL_PASSWORD=HrUserPass123 -p 3306:3306 -d mysql:8.1
